### ISSUE TITLE
Onduidelijk hoe ik specifieke post aanduid met id

### ISSUE THREAD

**Issue by hoyhymho** [hoyhymho/WAD-Opdracht#10]
Het gaat over mijn detailpagina:
```
          <Route
            path="/post/:id"
            render={
              ({match}) => {
                const id = match.params.id;
                // console.log(store.posts.id)
                return (store.posts.id) ? <PostDetail 
                store={store} id={id} post={store.posts.id}
                /> :<NotFound/>
              }
            }
          />
```
https://github.com/hoyhymho/WAD-Opdracht/blob/7e28f4bc33fe36bc23566dbcfbd5a633364e034e/my-reddit/src/App.js#L32

Voor dat alles in de store werd gestoken werd de post aangeroepen met posts[id], maar nu zit de id binnenin een array object en ik snap niet goed hoe ik die dan moet aanspreken. 

de eerste post is posts[0] en daar zit een id in

en een extra vraag:
als ik console.log(store.posts) doe, zie ik gewoon een ObservableArray met een hele lijst van nummers. Is er een manier om de inhoud van die array te tonen zonder naar de React tab te gaan en zoeken naar Posts en binnen hun nests pas te kunnen zien?

**Comment by SimonVanherweghe** [comment]
Je kan een item met specifieke ID uit een array halen met de array.find, zie oplossing labo
`const order = this.orders.find(check => check.drink.id === drink.id);`

Het loggen kan idd wat moeilijker zijn, dat is een nadeel
