### ISSUE TITLE
node server.js error in eigen opdracht

### ISSUE THREAD

**Issue by hoyhymho** [hoyhymho/WAD-Opdracht#14]
```
HoyHyms-MacBook-Pro:server hoyhym$ node server.js
Server luistert op poort 4000
Error, exiting

```

Op de moment is de client/server structuur van de les gekopieerd en alles van "tweet" naar "post" veranderd. Mis ik nog ergens iets?

**Comment by SimonVanherweghe** [comment]
ik veronderstel dat de database niet draait? `mongod` uitvoeren in een andere terminal sessie
