### ISSUE TITLE
waarvoor staan deze underscores in de operations van de labo-les?

### ISSUE THREAD

**Issue by hoyhymho** [hoyhymho/WAD-Opdracht#16]
```
 Mutation: {
    addTopic(_, args) {
      return new Topic(args).save();
    },
    addPost(_, args) {
      return new Post(args).save();
    }
}
```

of waarvoor dienen ze?

**Comment by SimonVanherweghe** [comment]
In ons geval is dat de `rootValue`
https://www.apollographql.com/docs/graphql-tools/resolvers#Resolver-function-signature
Dit maakt het mogelijk dat we onze resolvers, resultaten, kunnen nesten.

We hebben dat normaal nooit nodig, en dan kunnen we daar een _ plaatsen
