### ISSUE TITLE
Cannot read property 'writeData' of undefined - bij inloggen

### ISSUE THREAD

**Issue by hoyhymho** [hoyhymho/WAD-Opdracht#19]
ook al toont de server terminal venster een "login ok", krijg ik deze error in de app zelf boven de login button. 

ik veronderstel dat het naar deze lijn wijst?
https://github.com/hoyhymho/WAD-Opdracht/blob/0c83940084b59232bf1d72e90d8a00cf4bfb77c2/client/src/components/Login.jsx#L24

en ik heb de props meegegeven aan <Login />

**Comment by SimonVanherweghe** [comment]
Ik krijg 'deze error' niet te zien.

Maar je hebt geen defaults opgegeven in de index.js, bij het aanmaken van de client.
Dan zal je idd een fout krijgen als je wil schrijven naar de local cache
