### ISSUE TITLE
Probleem met alle inputs in een <Form /> groeperen

### ISSUE THREAD

**Issue by hoyhymho** [hoyhymho/WAD-Opdracht#4]
Op de moment heb ik een in de App een <Post /> met verschillende <Input />'s dat met
https://github.com/hoyhymho/WAD-Opdracht/blob/7af6ddc9fcd342c99f1547e91b9dc407eea9548a/my-reddit/src/App.js#L31 
wordt doorgegeven aan 
https://github.com/hoyhymho/WAD-Opdracht/blob/7af6ddc9fcd342c99f1547e91b9dc407eea9548a/my-reddit/src/App.js#L21

Ik probeer dan alle inputs te groeperen in een Form component 
https://github.com/hoyhymho/WAD-Opdracht/blob/7af6ddc9fcd342c99f1547e91b9dc407eea9548a/my-reddit/src/App.js#L55

maar ik begrijp dan niet zo goed hoe ik de juiste input "info" doorgeef aan de App

```
const Form = ({value, onChange}) => {

    const handleChangeValue = (e, info) => {
        const {value} = e.currentTarget
        onChange(value,info);
    }
    
    return (
        <div className="edit-post">
            <label className="inputLabel" htmlFor="title">Title</label>
            <input 
                type="text"
                id="title"
                onChange={handleChangeValue(e, "title")}
            />
        </div>
    );
}

```

**Comment by SimonVanherweghe** [comment]
Je zal eerst en vooral de info ergens vandaan moeten halen. Je kan dit doen zoals we in het labo deden, uit het name attribuut van het input field halen bijvoorbeeld.
https://github.com/hoyhymho/WAD-Opdracht/blob/7af6ddc9fcd342c99f1547e91b9dc407eea9548a/my-reddit/src/Form.jsx#L9

Je krijgt die waarde dan binnen als parameters in jouw inline functie voor onChange, maar je gebruikt nu momenteel enkel de 'value'
https://github.com/hoyhymho/WAD-Opdracht/blob/7af6ddc9fcd342c99f1547e91b9dc407eea9548a/my-reddit/src/App.js#L55

**Comment by hoyhymho** [comment]
Ah ok het lukt merci!
