### ISSUE TITLE
Wat betekent deze code?  

### ISSUE THREAD

**Issue by hoyhymho** [hoyhymho/WAD-Opdracht#6]
https://github.com/hoyhymho/WAD-Opdracht/blob/0bb6b1203c71669c66398a14bcff77abe9d52fd8/my-reddit/src/App.js#L70

```
return (posts[id]) ? <PostDetail 
post ={posts[id]} 
/> :<NotFound/>
```
Kan de bovenstaande code voluit geschreven worden? Ik wou het voluit schrijven om het beter te begrijpen.

Ik dacht dat het zoals een if else werkte en heb dit geprobeerd:

```
                return (
                  if(posts[id]) {
                    <PostDetail 
                    post ={posts[id]} 
                    /> 
                  }else{
                    <NotFound/>
                  }
                ) 
```

maar dat werkt niet

**Comment by SimonVanherweghe** [comment]
Ze werken inderdaad op eenzelfde manier, maar je moet ze wel correct gebruiken.
Die 'short if' kan je op 1 lijn zetten en zal 1 waarde returnen
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

Als je het voluit zou willen schrijven, dan moet je zowel een return statement in de true en in de false condition zetten. Een if statement op zich _returned_ niks
