### ISSUE TITLE
"Uncaught TypeError: _this.setState is not a function" bij setState in store

### ISSUE THREAD

**Issue by hoyhymho** [hoyhymho/WAD-Opdracht#8]
Ik heb MobX aan mijn project toegevoegd en al mijn functies en de state naar de store verplaatst. Maar als ik binnen de store de state wil updaten met setState krijg ik de bovenstaande error.

Bv. als ik op de delete knop wil drukken krijg ik de error en verwijst het me naar deze lijn code:
https://github.com/hoyhymho/WAD-Opdracht/blob/d33c0af89bb81e9c4e1ab41a61fb830326e36c34/my-reddit/src/store/store.js#L30

Of is het zelfs niet de bedoeling dat ik nog altijd state gebruik binnen de store?

**Comment by SimonVanherweghe** [comment]
Neen, het is inderdaad niet nodig om nog via de state te werken in de store, die vervangt dat (of zorgt voor een tussenoplossing)
Je mag uw posts bijhouden als property in de store, zie labo oefening (oplossing staat op Leho)
